# -*- coding: utf-8 -*-
"""Chicken analyses

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106y3nvHw7f6BcarxzY-cRf3kL3dX0xSA
"""

!pip install reportlab

import pandas as pd
import numpy as np
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

file_path = "Sale Report - Item Wise-Nov 18, 2025-Feb 25, 2026-490.xlsx"
df = pd.read_excel(file_path)

# =========================
# BASIC CLEANING
# =========================
df["date"] = pd.to_datetime(df["date"], errors="coerce", utc=True)
df["date"] = df["date"].dt.tz_convert("Asia/Kolkata").dt.tz_localize(None)

df = df[df["billed_by"] == "sw-noida-cashier"].copy()

df["saleUnitPrice"] = pd.to_numeric(df["saleUnitPrice"], errors="coerce")
df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")
df["totalAmount"] = pd.to_numeric(df["totalAmount"], errors="coerce")

df = df.dropna(subset=["brand","category","saleUnitPrice","name"])

# =========================
# CATEGORY NORMALIZATION
# =========================
df["category"] = df["category"].astype(str).str.strip().str.lower()

df["category"] = df["category"].replace({
    r".*jewel.*": "Jewellery",
    r".*bag.*": "Bags",
    r".*(cosmetic|makeup).*": "Cosmetics",
    r".*skin.*": "Skincare",
    r".*(f&b|food|beverage).*": "Beverages",
    r".*live.*menu.*": "Live Menu",
    r".*snack.*": "Snack Spot",
    r".*frag.*": "Fragrances",
    r".*style.*": "Style Studio",
    r".*croch.*": "Crochet",
    r".*croch.*": "Crochet",
    r".*tedd.*": "Teddy",
}, regex=True)

allowed_categories = [
    "Jewellery","Bags","Cosmetics","Skincare",
    "Beverages","Live Menu","Snack Spot","Fragrances", "Style Studio", "Crochet", "Teddy"
]

df = df[df["category"].isin(allowed_categories)].copy()

# =========================
# CREATE SINGLE PRICE RANGE PER PRODUCT
# =========================
product_base = (
    df.groupby(["category","brand","name"], as_index=False)
    .agg(
        total_sales=("totalAmount","sum"),
        units_sold=("quantity","sum"),
        min_price=("saleUnitPrice","min"),
        max_price=("saleUnitPrice","max")
    )
)

# round to 100 bands
product_base["range_start"] = (product_base["min_price"] // 50) * 50
product_base["range_end"] = (np.ceil(product_base["max_price"] / 50)) * 50

product_base["price_range"] = (
    "[" + product_base["range_start"].astype(int).astype(str)
    + ", "
    + product_base["range_end"].astype(int).astype(str)
    + ")"
)

product_summary = product_base[
    ["category","brand","name","price_range","total_sales","units_sold"]
].sort_values(["category","brand","name"])

# =========================
# EXPORT PRODUCT REPORT
# =========================
product_summary.to_excel(
    "SW_Noida_Category_Product_PriceRange_Report.xlsx",
    index=False
)

print("Excel Exported: SW_Noida_Category_Product_PriceRange_Report.xlsx")

# =========================
# CATEGORY LEVEL DOMINANT RANGE
# =========================
df["range_start"] = (df["saleUnitPrice"] // 50) * 50
df["range_end"] = (np.ceil(df["saleUnitPrice"] / 50)) * 50
df["price_range"] = "[" + df["range_start"].astype(int).astype(str) + ", " + df["range_end"].astype(int).astype(str) + ")"

category_price_range = (
    df.groupby(["category","price_range"], as_index=False)
    .agg(
        total_sales=("totalAmount","sum"),
        units_sold=("quantity","sum")
    )
)

category_top = (
    category_price_range
    .sort_values("total_sales", ascending=False)
    .groupby("category", as_index=False)
    .first()
    .rename(columns={"price_range":"top_price_range"})
)

category_price_range = category_price_range.merge(
    category_top[["category","top_price_range"]],
    on="category",
    how="left"
)

# =========================
# BRAND LEVEL DOMINANT RANGE
# =========================
brand_price_range = (
    df.groupby(["category","brand","price_range"], as_index=False)
    .agg(
        total_sales=("totalAmount","sum"),
        units_sold=("quantity","sum")
    )
)

brand_top = (
    brand_price_range
    .sort_values("total_sales", ascending=False)
    .groupby(["category","brand"], as_index=False)
    .first()
    .rename(columns={"price_range":"top_price_range"})
)

brand_price_range = brand_price_range.merge(
    brand_top[["category","brand","top_price_range"]],
    on=["category","brand"],
    how="left"
)

with pd.ExcelWriter("SW_Noida_Category_Brand_PriceRange_Summary.xlsx") as writer:
    category_price_range.to_excel(writer, sheet_name="Category_PriceRange", index=False)
    brand_price_range.to_excel(writer, sheet_name="Brand_PriceRange", index=False)

print("Excel Exported: SW_Noida_Category_Brand_PriceRange_Summary.xlsx")

# =========================
# PDF PREVIEW
# =========================
pdf_file = "SW_Noida_Category_Product_PriceRange_Report.pdf"

doc = SimpleDocTemplate(pdf_file, pagesize=A4)
styles = getSampleStyleSheet()
elements = []

title = Paragraph(
    "SW Noida Store – Category Wise Product Price Range Report",
    styles["Title"]
)
elements.append(title)
elements.append(Spacer(1,12))

preview = product_summary.head(60).copy()

table_data = [list(preview.columns)] + preview.values.tolist()

table = Table(table_data, repeatRows=1)
table.setStyle(TableStyle([
    ('BACKGROUND',(0,0),(-1,0),colors.grey),
    ('TEXTCOLOR',(0,0),(-1,0),colors.whitesmoke),
    ('GRID',(0,0),(-1,-1),1,colors.black),
    ('FONTSIZE',(0,0),(-1,-1),8),
]))

elements.append(table)
doc.build(elements)

print("PDF Exported:", pdf_file)

import pandas as pd
import numpy as np
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

# =========================
# LOAD DATA
# =========================
file_path = "Sale Report - Item Wise-Nov 18, 2025-Feb 17, 2026-427.xlsx"
df = pd.read_excel(file_path)

def audit(label, frame):
    print("\n====", label, "====")
    print("rows:", len(frame))
    print("total units:", frame["quantity"].sum())
    print("total sales:", frame["totalAmount"].sum())

audit("RAW LOADED", df)


# =========================
# BASIC CLEANING
# =========================
df["date"] = pd.to_datetime(df["date"], errors="coerce", utc=True)
df["date"] = df["date"].dt.tz_convert("Asia/Kolkata").dt.tz_localize(None)

# keep only required cashier
df = df[df["billed_by"] == "sw-noida-cashier"].copy()

# numeric conversion
df["saleUnitPrice"] = pd.to_numeric(df["saleUnitPrice"], errors="coerce")
df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")
df["totalAmount"] = pd.to_numeric(df["totalAmount"], errors="coerce")

# remove critical nulls
df = df.dropna(subset=["brand", "category", "saleUnitPrice", "name"])

# =========================
# CATEGORY NORMALIZATION (FIXED)
# =========================
# normalize everything to lowercase FIRST
df["category"] = df["category"].astype(str).str.strip().str.lower()

# map messy names → standardized lowercase labels
df["category"] = df["category"].replace({
    r".*jewel.*": "jewellery",
    r".*bag.*": "bags",
    r".*(cosmetic|makeup).*": "cosmetics",
    r".*skin.*": "skincare",
    r".*(f&b|food|beverage).*": "beverages",
    r".*live.*menu.*": "live menu",
    r".*snack.*": "snack spot",
    r".*frag.*": "fragrances"
}, regex=True)

allowed_categories = [
    "jewellery", "bags", "cosmetics", "skincare",
    "beverages", "live menu", "snack spot", "fragrances"
]

# IMPORTANT: this filter no longer removes half your data
df = df[df["category"].isin(allowed_categories)].copy()

# =========================
# CREATE SINGLE PRICE RANGE PER PRODUCT
# =========================
product_base = (
    df.groupby(["category", "brand", "name"], as_index=False)
    .agg(
        total_sales=("totalAmount", "sum"),
        units_sold=("quantity", "sum"),
        min_price=("saleUnitPrice", "min"),
        max_price=("saleUnitPrice", "max")
    )
)

# 50-rupee price bands
product_base["range_start"] = (product_base["min_price"] // 50) * 50
product_base["range_end"] = (np.ceil(product_base["max_price"] / 50)) * 50

product_base["price_range"] = (
    "[" + product_base["range_start"].astype(int).astype(str)
    + ", "
    + product_base["range_end"].astype(int).astype(str)
    + ")"
)

product_summary = product_base[
    ["category", "brand", "name", "price_range", "total_sales", "units_sold"]
].sort_values(["category", "brand", "name"])

# =========================
# EXPORT PRODUCT REPORT
# =========================
product_summary.to_excel(
    "SW_Noida_Category_Product_PriceRange_Report.xlsx",
    index=False
)

print("Excel Exported: SW_Noida_Category_Product_PriceRange_Report.xlsx")

# =========================
# CATEGORY LEVEL DOMINANT RANGE
# =========================
df["range_start"] = (df["saleUnitPrice"] // 50) * 50
df["range_end"] = (np.ceil(df["saleUnitPrice"] / 50)) * 50

df["price_range"] = (
    "[" + df["range_start"].astype(int).astype(str)
    + ", "
    + df["range_end"].astype(int).astype(str)
    + ")"
)

category_price_range = (
    df.groupby(["category", "price_range"], as_index=False)
    .agg(
        total_sales=("totalAmount", "sum"),
        units_sold=("quantity", "sum")
    )
)

category_top = (
    category_price_range
    .sort_values("total_sales", ascending=False)
    .groupby("category", as_index=False)
    .first()
    .rename(columns={"price_range": "top_price_range"})
)

category_price_range = category_price_range.merge(
    category_top[["category", "top_price_range"]],
    on="category",
    how="left"
)

# =========================
# BRAND LEVEL DOMINANT RANGE
# =========================
brand_price_range = (
    df.groupby(["category", "brand", "price_range"], as_index=False)
    .agg(
        total_sales=("totalAmount", "sum"),
        units_sold=("quantity", "sum")
    )
)

brand_top = (
    brand_price_range
    .sort_values("total_sales", ascending=False)
    .groupby(["category", "brand"], as_index=False)
    .first()
    .rename(columns={"price_range": "top_price_range"})
)

brand_price_range = brand_price_range.merge(
    brand_top[["category", "brand", "top_price_range"]],
    on=["category", "brand"],
    how="left"
)

with pd.ExcelWriter("SW_Noida_Category_Brand_PriceRange_Summary.xlsx") as writer:
    category_price_range.to_excel(writer, sheet_name="Category_PriceRange", index=False)
    brand_price_range.to_excel(writer, sheet_name="Brand_PriceRange", index=False)

print("Excel Exported: SW_Noida_Category_Brand_PriceRange_Summary.xlsx")

# =========================
# PDF PREVIEW
# =========================
pdf_file = "SW_Noida_Category_Product_PriceRange_Report.pdf"

doc = SimpleDocTemplate(pdf_file, pagesize=A4)
styles = getSampleStyleSheet()
elements = []

title = Paragraph(
    "SW Noida Store – Category Wise Product Price Range Report",
    styles["Title"]
)
elements.append(title)
elements.append(Spacer(1, 12))

preview = product_summary.head(60).copy()
table_data = [list(preview.columns)] + preview.values.tolist()

table = Table(table_data, repeatRows=1)
table.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,0), colors.grey),
    ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
    ('GRID', (0,0), (-1,-1), 1, colors.black),
    ('FONTSIZE', (0,0), (-1,-1), 8),
]))

elements.append(table)
doc.build(elements)

print("PDF Exported:", pdf_file)

# after cashier filter
df = df[df["billed_by"] == "sw-noida-cashier"].copy()
audit("AFTER CASHIER FILTER", df)

# after dropna
df = df.dropna(subset=["brand","category","saleUnitPrice","name"])
audit("AFTER DROPNA", df)

# after category filtering
df = df[df["category"].isin(allowed_categories)].copy()
audit("AFTER CATEGORY FILTER", df)

import pandas as pd
import numpy as np

file_path = "Sale Report - Item Wise-Nov 18, 2025-Feb 17, 2026-427.xlsx"
df = pd.read_excel(file_path)

df["date"] = pd.to_datetime(df["date"], errors="coerce", utc=True)
df["date"] = df["date"].dt.tz_convert("Asia/Kolkata").dt.tz_localize(None)

df = df[df["billed_by"] == "sw-noida-cashier"].copy()

df["saleUnitPrice"] = pd.to_numeric(df["saleUnitPrice"], errors="coerce")
df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")
df["totalAmount"] = pd.to_numeric(df["totalAmount"], errors="coerce")

df = df.dropna(subset=["brand","category","saleUnitPrice"])

df["category"] = df["category"].astype(str).str.strip().str.lower()

category_map = {
    "jewellery": "Jewellery",
    "jewelry": "Jewellery",
    "bags": "Bags",
    "cosmetics": "Cosmetics",
    "makeup": "Cosmetics",
    "skincare": "Skincare",
    "skin care": "Skincare",
    "f&b": "Beverages",
    "beverages": "Beverages",
    "food & beverage": "Beverages",
    "live menu": "Live Menu",
    "livemenu": "Live Menu"
}

df["category"] = df["category"].map(category_map)

allowed_categories = [
    "Jewellery",
    "Bags",
    "Cosmetics",
    "Skincare",
    "Beverages",
    "Live Menu"
]

df = df[df["category"].isin(allowed_categories)].copy()

bins = np.arange(0, 5200, 200)
df["price_range"] = pd.cut(df["saleUnitPrice"], bins=bins, right=False)

category_price_range = (
    df.groupby(["category","price_range"], observed=True, as_index=False)
    .agg(
        total_sales=("totalAmount","sum"),
        units_sold=("quantity","sum")
    )
    .sort_values(["category","price_range"])
)

idx_cat = category_price_range.groupby("category")["total_sales"].idxmax()

top_cat_range = category_price_range.loc[idx_cat][
    ["category","price_range"]
].rename(columns={"price_range":"top_price_range"})

category_price_range = category_price_range.merge(
    top_cat_range,
    on="category",
    how="left"
)

brand_price_range = (
    df.groupby(["category","brand","price_range"], observed=True, as_index=False)
    .agg(
        total_sales=("totalAmount","sum"),
        units_sold=("quantity","sum")
    )
    .sort_values(["category","brand","price_range"])
)

idx_brand = brand_price_range.groupby(["category","brand"])["total_sales"].idxmax()

top_brand_range = brand_price_range.loc[idx_brand][
    ["category","brand","price_range"]
].rename(columns={"price_range":"top_price_range"})

brand_price_range = brand_price_range.merge(
    top_brand_range,
    on=["category","brand"],
    how="left"
)

with pd.ExcelWriter("SW_Noida_Brand_Category_PriceRange_Only.xlsx") as writer:
    category_price_range.to_excel(writer, sheet_name="Category_PriceRange", index=False)
    brand_price_range.to_excel(writer, sheet_name="Brand_PriceRange", index=False)

print("Exported: SW_Noida_Brand_Category_PriceRange_Only.xlsx")

import pandas as pd
import numpy as np

file_path = "Sale Report - Item Wise-Nov 18, 2025-Feb 17, 2026-427.xlsx"
df = pd.read_excel(file_path)

# =========================
# TIME CLEANING
# =========================
df["date"] = pd.to_datetime(df["date"], errors="coerce", utc=True)
df["date"] = df["date"].dt.tz_convert("Asia/Kolkata").dt.tz_localize(None)

df = df[df["billed_by"] == "sw-noida-cashier"].copy()

df["saleUnitPrice"] = pd.to_numeric(df["saleUnitPrice"], errors="coerce")
df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")
df["totalAmount"] = pd.to_numeric(df["totalAmount"], errors="coerce")

df = df.dropna(subset=["brand","category","saleUnitPrice"])

# =========================
# DAY NIGHT SPLIT (9AM-7PM / 7PM-6AM)
# =========================
hour = df["date"].dt.hour

df["day_night"] = np.select(
    [
        (hour >= 9) & (hour < 19),
        (hour >= 19) | (hour < 6)
    ],
    ["DAY","NIGHT"],
    default="OTHER"
)

df = df[df["day_night"].isin(["DAY","NIGHT"])].copy()

# =========================
# CATEGORY NORMALIZATION
# =========================
df["category"] = df["category"].astype(str).str.strip().str.lower()

category_map = {
    "jewellery": "Jewellery",
    "jewelry": "Jewellery",
    "bags": "Bags",
    "cosmetics": "Cosmetics",
    "makeup": "Cosmetics",
    "skincare": "Skincare",
    "skin care": "Skincare",
    "f&b": "Beverages",
    "beverages": "Beverages",
    "food & beverage": "Beverages",
    "live menu": "Live Menu",
    "livemenu": "Live Menu"
}

df["category"] = df["category"].map(category_map)

allowed_categories = [
    "Jewellery",
    "Bags",
    "Cosmetics",
    "Skincare",
    "Beverages",
    "Live Menu"
]

df = df[df["category"].isin(allowed_categories)].copy()

# =========================
# PRICE RANGE CREATION
# =========================
bins = np.arange(0, 5200, 200)
df["price_range"] = pd.cut(df["saleUnitPrice"], bins=bins, right=False)

# =====================================================
# CATEGORY PRICE RANGE — DAY NIGHT SPLIT
# =====================================================
category_price_range = (
    df.groupby(["category","price_range","day_night"], observed=True, as_index=False)
    .agg(
        total_sales=("totalAmount","sum"),
        units_sold=("quantity","sum")
    )
)

category_price_range = (
    category_price_range
    .pivot_table(
        index=["category","price_range"],
        columns="day_night",
        values=["total_sales","units_sold"],
        fill_value=0
    )
)

category_price_range.columns = [
    f"{c[0]}_{c[1].lower()}" for c in category_price_range.columns
]

category_price_range = category_price_range.reset_index()

# 🔥 COMBINED SALES FOR TOP RANGE
category_price_range["total_sales_combined"] = (
    category_price_range.get("total_sales_day",0) +
    category_price_range.get("total_sales_night",0)
)

idx_cat = category_price_range.groupby("category")["total_sales_combined"].idxmax()

top_cat_range = category_price_range.loc[idx_cat][
    ["category","price_range"]
].rename(columns={"price_range":"top_price_range"})

category_price_range = category_price_range.merge(
    top_cat_range,
    on="category",
    how="left"
)

# =====================================================
# BRAND PRICE RANGE — DAY NIGHT SPLIT
# =====================================================
brand_price_range = (
    df.groupby(["category","brand","price_range","day_night"], observed=True, as_index=False)
    .agg(
        total_sales=("totalAmount","sum"),
        units_sold=("quantity","sum")
    )
)

brand_price_range = (
    brand_price_range
    .pivot_table(
        index=["category","brand","price_range"],
        columns="day_night",
        values=["total_sales","units_sold"],
        fill_value=0
    )
)

brand_price_range.columns = [
    f"{c[0]}_{c[1].lower()}" for c in brand_price_range.columns
]

brand_price_range = brand_price_range.reset_index()

brand_price_range["total_sales_combined"] = (
    brand_price_range.get("total_sales_day",0) +
    brand_price_range.get("total_sales_night",0)
)

idx_brand = brand_price_range.groupby(["category","brand"])["total_sales_combined"].idxmax()

top_brand_range = brand_price_range.loc[idx_brand][
    ["category","brand","price_range"]
].rename(columns={"price_range":"top_price_range"})

brand_price_range = brand_price_range.merge(
    top_brand_range,
    on=["category","brand"],
    how="left"
)

# =====================================================
# EXPORT
# =====================================================
with pd.ExcelWriter("SW_Noida_Brand_Category_PriceRange_DayNight.xlsx") as writer:
    category_price_range.to_excel(writer, sheet_name="Category_PriceRange", index=False)
    brand_price_range.to_excel(writer, sheet_name="Brand_PriceRange", index=False)

print("Exported: SW_Noida_Brand_Category_PriceRange_DayNight.xlsx")

import pandas as pd
import numpy as np

# =====================================================
# FILE PATHS
# =====================================================
sales_file = "Sale Report - Item Wise-Nov 18, 2025-Feb 25, 2026-490.xlsx"
stock_file = "Stock Report-Feb 25, 2026-Feb 25, 2026-488.xlsx"

# =====================================================
# LOAD FILES
# =====================================================
df = pd.read_excel(sales_file)
stock = pd.read_excel(stock_file)

df.columns = df.columns.str.strip().str.lower()
stock.columns = stock.columns.str.strip().str.lower()

df = df.loc[:, ~df.columns.duplicated()]
stock = stock.loc[:, ~stock.columns.duplicated()]

# =====================================================
# 🔥 CLEAN SKU — USE SALES SKU AS MASTER KEY
# =====================================================
if "code" in stock.columns:
    stock["sku"] = stock["code"]

df["sku"] = df["sku"].astype(str).str.strip().str.lstrip("0")
stock["sku"] = stock["sku"].astype(str).str.strip().str.lstrip("0")

# =====================================================
# 🔥 BUILD SKU LIFECYCLE TABLE FROM STOCK
# =====================================================
stock["createdat"] = pd.to_datetime(
    stock["createdat"],
    errors="coerce"
).dt.normalize()

sku_lifecycle = (
    stock[["sku","createdat"]]
    .dropna(subset=["sku","createdat"])
    .drop_duplicates("sku")
)

# =====================================================
# 🔥 WORKING DAYS = TODAY - CREATEDAT (EXCLUDE SAT/SUN)
# =====================================================
today = pd.Timestamp.today().normalize()
end_date = today + pd.Timedelta(days=1)

start = sku_lifecycle["createdat"].values.astype("datetime64[D]")
end = np.repeat(end_date.to_datetime64().astype("datetime64[D]"), len(start))

sku_lifecycle["working_days_live"] = np.busday_count(start, end)

# =====================================================
# 🔥 MERGE WORKING DAYS INTO SALES USING SKU
# =====================================================
df = df.merge(
    sku_lifecycle[["sku","working_days_live"]],
    on="sku",
    how="left"
)

# =====================================================
# SALES CLEANING
# =====================================================
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df = df[df["billed_by"] == "sw-noida-cashier"].copy()

df["saleunitprice"] = pd.to_numeric(df["saleunitprice"], errors="coerce")
df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")

df = df.dropna(subset=["brand","category","saleunitprice","quantity"])

df["revenue"] = df["saleunitprice"] * df["quantity"]

# =====================================================
# CATEGORY NORMALIZATION
# =====================================================
df["category"] = df["category"].str.strip().str.lower()

category_map = {
    "jewellery":"Jewellery",
    "jewelry":"Jewellery",
    "bags":"Bags",
    "cosmetics":"Cosmetics",
    "makeup":"Cosmetics",
    "skincare":"Skincare",
    "skin care":"Skincare",
    "f&b":"Beverages",
    "beverages":"Beverages",
    "food & beverage":"Beverages",
    "live menu":"Live Menu",
    "livemenu":"Live Menu"
}

df["category"] = df["category"].map(category_map)

allowed_categories = [
    "Jewellery","Bags","Cosmetics","Skincare","Beverages","Live Menu"
]

df = df[df["category"].isin(allowed_categories)]

# =====================================================
# PRICE RANGE — ₹50 BUCKETS
# =====================================================
max_price = int(df["saleunitprice"].max() + 100)
bins = np.arange(0, max_price, 50)

df["price_range"] = pd.cut(df["saleunitprice"], bins=bins, right=False)

# =====================================================
# BRAND PRICE RANGE ANALYSIS (ONE WORKING DAY COLUMN)
# =====================================================
brand_price_range = (
    df.groupby(["category","brand","price_range"], observed=True)
    .agg(
        total_sales=("revenue","sum"),
        units_sold=("quantity","sum"),
        avg_working_days=("working_days_live","mean")
    )
    .reset_index()
)

brand_price_range.to_excel(
    "SW_Noida_Brand_PriceRange_50Buckets.xlsx",
    index=False
)

print("Exported successfully")

import pandas as pd
import numpy as np
import re

file_path = "Sale Report - Item Wise-Nov 18, 2025-Feb 17, 2026-427.xlsx"
df = pd.read_excel(file_path)

df["date"] = pd.to_datetime(df["date"], errors="coerce", utc=True)
df["date"] = df["date"].dt.tz_convert("Asia/Kolkata").dt.tz_localize(None)

df = df[df["billed_by"] == "sw-noida-cashier"].copy()

df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")
df["totalAmount"] = pd.to_numeric(df["totalAmount"], errors="coerce")

df["category"] = df["category"].astype(str).str.strip().str.lower()

category_map = {
    "cosmetics": "Cosmetics",
    "makeup": "Cosmetics",
    "skincare": "Skincare",
    "skin care": "Skincare"
}

df["category"] = df["category"].map(category_map)

df = df[df["category"].isin(["Cosmetics","Skincare"])].copy()

def clean_first_name(x):
    if pd.isna(x):
        return np.nan
    x = re.sub(r"[^A-Za-z\s]", "", str(x)).strip()
    if x == "":
        return np.nan
    return x.split()[0].lower()

df["first_name"] = df["customerName"].apply(clean_first_name)
df["customerMobile"] = df["customerMobile"].astype(str).str.strip()

def make_customer_display(row):
    name = row["first_name"]
    phone = row["customerMobile"]

    if pd.notna(name) and phone not in ["nan","None",""]:
        return f"{name} - {phone}"
    if pd.notna(name):
        return name
    if phone not in ["nan","None",""]:
        return phone
    return "unknown_customer"

df["customer_display"] = df.apply(make_customer_display, axis=1)

df = df[df["customer_display"] != "unknown_customer"].copy()
df = df[df["customerMobile"].notna()].copy()

value_summary = (
    df.groupby(["category","customer_display"], as_index=False)
    .agg(total_value=("totalAmount","sum"))
)

top5_skincare_value = (
    value_summary[value_summary["category"]=="Skincare"]
    .sort_values("total_value", ascending=False)
    .head(5)
)

top5_cosmetics_value = (
    value_summary[value_summary["category"]=="Cosmetics"]
    .sort_values("total_value", ascending=False)
    .head(5)
)

volume_summary = (
    df.groupby(["category","customer_display"], as_index=False)
    .agg(total_units=("quantity","sum"))
)

top5_skincare_volume = (
    volume_summary[volume_summary["category"]=="Skincare"]
    .sort_values("total_units", ascending=False)
    .head(5)
)

top5_cosmetics_volume = (
    volume_summary[volume_summary["category"]=="Cosmetics"]
    .sort_values("total_units", ascending=False)
    .head(5)
)

print("\nTOP 5 SKINCARE — VALUE WISE")
print(top5_skincare_value)

print("\nTOP 5 SKINCARE — VOLUME WISE")
print(top5_skincare_volume)

print("\nTOP 5 COSMETICS — VALUE WISE")
print(top5_cosmetics_value)

print("\nTOP 5 COSMETICS — VOLUME WISE")
print(top5_cosmetics_volume)

with pd.ExcelWriter("Top5_Consumers_Skincare_Cosmetics.xlsx") as writer:
    top5_skincare_value.to_excel(writer, sheet_name="Skincare_Value", index=False)
    top5_skincare_volume.to_excel(writer, sheet_name="Skincare_Volume", index=False)
    top5_cosmetics_value.to_excel(writer, sheet_name="Cosmetics_Value", index=False)
    top5_cosmetics_volume.to_excel(writer, sheet_name="Cosmetics_Volume", index=False)

print("\nExported: Top5_Consumers_Skincare_Cosmetics.xlsx")

import pandas as pd
import numpy as np

file_path = "Sale Report - Item Wise-Nov 18, 2025-Feb 17, 2026-427.xlsx"
df = pd.read_excel(file_path)

# ==========================
# BASIC CLEANING
# ==========================
df = df[df["billed_by"] == "sw-noida-cashier"].copy()

df["saleUnitPrice"] = pd.to_numeric(df["saleUnitPrice"], errors="coerce")
df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")
df["totalAmount"] = pd.to_numeric(df["totalAmount"], errors="coerce")

df = df.dropna(subset=["category","saleUnitPrice"])

# ==========================
# FILTER COSMETICS ONLY
# ==========================
df["category"] = df["category"].astype(str).str.strip().str.lower()

df = df[df["category"].isin(["cosmetics","makeup"])].copy()

# ==========================
# CREATE PRICE BANDS (₹100 RANGE)
# ==========================
bins = np.arange(0, 5200, 100)
df["price_range"] = pd.cut(df["saleUnitPrice"], bins=bins, right=False)

# ==========================
# CALCULATE SALES PER BAND
# ==========================
cosmetics_ranges = (
    df.groupby("price_range", observed=True)
    .agg(
        total_sales=("totalAmount","sum"),
        total_units=("quantity","sum")
    )
    .reset_index()
    .sort_values("price_range")
)

# ==========================
# FIND DOMINANT PRICE RANGE
# ==========================
top_range = cosmetics_ranges.loc[
    cosmetics_ranges["total_sales"].idxmax()
]

print("\nDominant Cosmetics Price Range:")
print(top_range)

# ==========================
# EXPORT EXCEL
# ==========================
cosmetics_ranges.to_excel(
    "SW_Noida_Cosmetics_PriceBand_Only.xlsx",
    index=False
)

print("\nExported: SW_Noida_Cosmetics_PriceBand_Only.xlsx")

import pandas as pd

# =========================
# LOAD FILES
# =========================
sales_file = "Sale Report - Item Wise-Nov 18, 2025-Feb 17, 2026-427.xlsx"
stock_file = "Stock Report-Nov 18, 2025-Feb 17, 2026-435.xlsx"

sales_df = pd.read_excel(sales_file)
stock_df = pd.read_excel(stock_file)

# =========================
# CLEAN SKU
# =========================
def clean_sku(x):
    if pd.isna(x):
        return None
    return str(x).strip().replace(".0","")

sales_df["sku"] = sales_df["sku"].apply(clean_sku)
stock_df["sku"] = stock_df["sku"].apply(clean_sku)

sales_df["quantity"] = pd.to_numeric(sales_df["quantity"], errors="coerce").fillna(0)

sales_df = sales_df[
    sales_df["billed_by"] == "sw-noida-cashier"
].copy()

# =====================================================
# 🔥 CRITICAL FIX — BILL LEVEL DEDUPLICATION
# =====================================================
bill_sku = (
    sales_df
    .groupby(["number","sku"], as_index=False)
    .agg(qty_per_bill=("quantity","sum"))
)

# now aggregate TRUE sales per SKU
sales_summary = (
    bill_sku
    .groupby("sku", as_index=False)
    .agg(total_sales_qty=("qty_per_bill","sum"))
)

# =====================================================
# MERGE WITH STOCK
# =====================================================
merged = stock_df.merge(
    sales_summary,
    on="sku",
    how="left",
    indicator=True
)

merged["total_sales_qty"] = merged["total_sales_qty"].fillna(0)

print("\nMerge Match Summary:")
print(merged["_merge"].value_counts())

# =====================================================
# FILTER ABSOLUTE 0 OR 1 SALES
# =====================================================
low_sales_products = merged[
    merged["total_sales_qty"].isin([0,1])
].copy()

# =====================================================
# EXPORT
# =====================================================
output_file = "Noida_Zero_And_One_Sales_Products.xlsx"
low_sales_products.to_excel(output_file, index=False)

print("\nExported:", output_file)

import pandas as pd
import numpy as np

# ======================================
# LOAD FILE
# ======================================
file_path = "Sale Report - Item Wise-Feb 1, 2026-Feb 14, 2026-453.xlsx"
df = pd.read_excel(file_path)

# ======================================
# CLEAN COLUMNS
# ======================================
df.columns = df.columns.str.strip()

# Your actual columns:
# number = bill no
# date   = datetime
# totalAmount = line value
# billed_by = cashier id

# Convert datetime
df["date"] = pd.to_datetime(df["date"]).dt.tz_convert("Asia/Kolkata")

# Remove bad rows
df = df.dropna(subset=["date", "number"])

# ======================================
# FILTER ONLY REQUIRED CASHIER
# ======================================
df = df[df["billed_by"].str.lower() == "sw-noida-cashier"]

# ======================================
# CRITICAL STEP:
# Collapse line-items → unique bills
# ======================================
bill_df = (
    df.groupby("number", as_index=False)
      .agg({
          "date": "min",            # bill timestamp
          "totalAmount": "sum"      # full order value
      })
)

# ======================================
# CREATE TIME SEGMENTS
# ======================================
bill_df["hour"] = bill_df["date"].dt.hour

conditions = [
    (bill_df["hour"] >= 9) & (bill_df["hour"] < 19),
    (bill_df["hour"] >= 19) | (bill_df["hour"] < 6),
]

choices = [
    "09AM-07PM",
    "07PM-06AM"
]

bill_df["time_segment"] = np.select(conditions, choices, default="ignore")

# Drop 6AM–9AM gap (you didn't ask for it)
bill_df = bill_df[bill_df["time_segment"] != "ignore"]

# ======================================
# FINAL ANALYSIS
# ======================================
analysis = (
    bill_df
    .groupby("time_segment")
    .agg(
        transactions=("number", "nunique"),
        total_sales=("totalAmount", "sum"),
        avg_order_value=("totalAmount", "mean")
    )
    .reset_index()
)

# ======================================
# EXPORT TO EXCEL
# ======================================
output_file = "time_based_transaction_analysis.xlsx"

bill_df["date"] = bill_df["date"].dt.tz_localize(None)

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    analysis.to_excel(writer, sheet_name="analysis", index=False)
    bill_df.to_excel(writer, sheet_name="bill_level_data", index=False)

print("Exported:", output_file)

